version: '3.10'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: kitten
      POSTGRES_USER: newuser
      POSTGRES_PASSWORD: 123123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
