version: '3.10'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: kitten
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://newuser:123123@db:5432/kitten
    depends_on:
      - db

volumes:
  postgres_data:
